[package]
name = "tap-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal dependencies
tap-core = { path = "../tap-core" }
tap-agent = { path = "../tap-agent" }

# Async runtime
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"

# Utilities
log = "0.4"
tracing = "0.1"
dashmap = "5.4" # Concurrent HashMap implementation
uuid = { version = "1.3", features = ["v4", "serde"] }
futures = "0.3"
sha2 = "0.10"
base58 = "0.2"
chrono = "0.4"

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["async_tokio"] }
futures = "0.3"

[[bench]]
name = "stress_test"
harness = false
